name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-tests:
    name: Build and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint || echo "lint script missing"
      - run: pnpm test:unit || echo "unit tests missing"
      - run: pnpm build
      - run: npx playwright install --with-deps
      - run: pnpm test:e2e
